### Post a user:
POST http://localhost:8080/api/v1/users
Content-Type: application/json

{
  "name": "Admin",
  "email": "Admin@example.com",
  "password": "Abc!123Abc"
}
### Login as Noy(register user)
POST http://localhost:8080/api/v1/users/login
Content-Type: application/json

{
  "email": "noyy@email.com",
  "password": "Abc!123Abc"
}


### Login as Admin:
POST http://localhost:8080/api/v1/users/login
Content-Type: application/json

{
  "email": "Admin@example.com",
  "password": "Abc!123Abc"
}
 
### Get all users:
GET http://localhost:8080/api/v1/users
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJlbWFpbCI6IkFkbWluQGV4YW1wbGUuY29tIiwiaWQiOiI2NWNiYTUwOGNiNGM5MWUwZTBjM2FkMjciLCJpc0FkbWluIjp0cnVlLCJpYXQiOjE3MDc4NDQ5ODR9.eqLidaa_zWWtweQEhzi3Axh3u_g5mr1ZxF-JudbtYoQ



### get user by id without token - 400:
GET http://localhost:8080/api/v1/users/657ebb4cc105647ed8c60a9e


### get user by id with admin token - 200:
GET http://localhost:8080/api/v1/users/657ebb4cc105647ed8c60a9e
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJlbWFpbCI6IkFkbWluQGV4YW1wbGUuY29tIiwiaWQiOiI2NTdlYmI0YmMxMDU2NDdlZDhjNjBhOTYiLCJpc0FkbWluIjp0cnVlLCJpYXQiOjE3MDI4MDU2NjF9.6B2b0UZnktW2twLUDZdPAnwec9BRR2figujqwFyOBAQ


### get user by id with an id of another user (not admin): 401 Unauthorized
GET http://localhost:8080/api/v1/users/657ebb4cc105647ed8c60a9e
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJlbWFpbCI6IlJlZ3VsYXJAZXhhbXBsZS5jb20iLCJpZCI6IjY1N2ViYjRjYzEwNTY0N2VkOGM2MGFhNCIsImlzQWRtaW4iOmZhbHNlLCJpYXQiOjE3MDI4MDU3NDZ9.DcHF_4jLPHc8zFWWGvOi0uxEIBmrfxUYNNVSz5mdqjI



### update a user:
PUT http://localhost:8080/api/v1/users/657ec2c6c105647ed8c60ad1
Content-Type: application/json
Authorization: bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJlbWFpbCI6Im5veUBlbWFpbC5jb20iLCJpZCI6IjY1N2VjMmM2YzEwNTY0N2VkOGM2MGFkMSIsImlzQWRtaW4iOmZhbHNlLCJpYXQiOjE3MDI4MDY0MzJ9.fQxxhTxbA29BAyUusrsXv1rOhN2DQHx5FTWtPy1BqQ0

{
  "name": {
    "first": "NOY",
    "middle": "a",
    "last": "Cohen"
  },
  "phone": "0512345567",
  "email": "noy@email.com",
  "password": "Abc!123Abc",
  "address": {
    "state": "IL",
    "country": "Israel",
    "city": "Arad",
    "street": "Shoham",
    "houseNumber": 5,
    "zip": 8920435
  },
  "isBusiness": true
}


### partial update a user (only isBusiness):
PATCH http://localhost:8080/api/v1/users/657ec2c6c105647ed8c60ad1
Content-Type: application/json
Authorization: bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJlbWFpbCI6Im5veUBlbWFpbC5jb20iLCJpZCI6IjY1N2VjMmM2YzEwNTY0N2VkOGM2MGFkMSIsImlzQWRtaW4iOmZhbHNlLCJpYXQiOjE3MDI4MDY3OTB9.dDBxl9alM7QLa1gIuQYjKrV56nfMDvEI37jd3GgRQzc

{
  "isBusiness": true
}

### delete a user:
DELETE http://localhost:8080/api/v1/users/65645f92dde85faea9d3e380
Authorization: bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJlbWFpbCI6ImVsbHZpc0BlbWFpbC5jb20iLCJpZCI6IjY1NjQ1ZjkyZGRlODVmYWVhOWQzZTM4MCIsImlzQWRtaW4iOmZhbHNlLCJpYXQiOjE3MDEwNzY4OTV9.XSHs3UIAgz3qTppwdVvs9Ldpq5AbvtLH-pUPOC_CtDg


### get all cards:
GET http://localhost:8080/api/v1/cards

### get my cards:
GET http://localhost:8080/api/v1/cards/my-cards
Authorization: bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJlbWFpbCI6IkFkbWluQGV4YW1wbGUuY29tIiwiaWQiOiI2NTdlYmI0YmMxMDU2NDdlZDhjNjBhOTYiLCJpc0FkbWluIjp0cnVlLCJpYXQiOjE3MDI4MTIyNzF9.XjmFKYicKFyGhWEIBG1zrVqhW20eZW3_7u5_yVf8HAU

### get card by id:
GET http://localhost:8080/api/v1/cards/657ebb4cc105647ed8c60aac


### post a card:
POST http://localhost:8080/api/v1/cards
Content-Type: application/json
Authorization: bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJlbWFpbCI6IkFkbWluQGV4YW1wbGUuY29tIiwiaWQiOiI2NWNiYTUwOGNiNGM5MWUwZTBjM2FkMjciLCJpc0FkbWluIjp0cnVlLCJpYXQiOjE3MDc4NDQ5ODR9.eqLidaa_zWWtweQEhzi3Axh3u_g5mr1ZxF-JudbtYoQ

{
  "title": "product 1",
  "description": "Experienced software engineer with a passion for developing innovative programs that expedite the efficiency and effectiveness of organizational success.",
  "image": {
    "url": "https://picsum.photos/200",
    "alt": "John Doe"
  },
  "price":30
}

### update a card:
PUT http://localhost:8080/api/v1/cards/657eddf8704b3a28125d95cf
Content-Type: application/json
Authorization: bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJlbWFpbCI6Im5veUBlbWFpbC5jb20iLCJpZCI6IjY1N2VjMmM2YzEwNTY0N2VkOGM2MGFkMSIsImlzQWRtaW4iOmZhbHNlLCJpYXQiOjE3MDI4MTQ2NjZ9.lXfcu7NedSCP8vzeRnl-csI4jt3B7HaoxVSJBaGe4Eg

{
  "title": "not Marvel"
}

###like card
PATCH http://localhost:8080/api/v1/cards/657eddf8704b3a28125d95cf
Authorization: bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJlbWFpbCI6IkJ1c2luZXNzQGV4YW1wbGUuY29tIiwiaWQiOiI2NTdlYmI0Y2MxMDU2NDdlZDhjNjBhOWUiLCJpc0FkbWluIjpmYWxzZSwiaWF0IjoxNzAyODE1MzE0fQ.OaHJxCrrCfQBkqlQgSF1RMCLZftR8ETsy5LUdnR63r0

### delete card:
DELETE http://localhost:8080/api/v1/cards/65cbb4bdc49c93e7501f3a06
Authorization: bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJlbWFpbCI6IkFkbWluQGV4YW1wbGUuY29tIiwiaWQiOiI2NWNiYTUwOGNiNGM5MWUwZTBjM2FkMjciLCJpc0FkbWluIjp0cnVlLCJpYXQiOjE3MDc4NDQ5ODR9.eqLidaa_zWWtweQEhzi3Axh3u_g5mr1ZxF-JudbtYoQ