### Post a user:
POST http://localhost:8080/api/v1/users
Content-Type: application/json

{
  "name": "Admin",
  "email": "Admin@example.com",
  "password": "Abc!123Abc"
}
### Login as Noy(register user)
POST http://localhost:8080/api/v1/users/login
Content-Type: application/json

{
  "email": "noyy@email.com",
  "password": "Abc!123Abc"
}


### Login as Admin:
POST http://localhost:8080/api/v1/users/login
Content-Type: application/json

{
  "email": "Admin@example.com",
  "password": "Abc!123Abc"
}
 
### Get all users:
GET http://localhost:8080/api/v1/users
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJlbWFpbCI6IkFkbWluQGV4YW1wbGUuY29tIiwiaWQiOiI2NWNiYTUwOGNiNGM5MWUwZTBjM2FkMjciLCJpc0FkbWluIjp0cnVlLCJpYXQiOjE3MDc4NDQ5ODR9.eqLidaa_zWWtweQEhzi3Axh3u_g5mr1ZxF-JudbtYoQ



### get user by id without token - 400:
GET http://localhost:8080/api/v1/users/657ebb4cc105647ed8c60a9e


### get user by id with admin token - 200:
GET http://localhost:8080/api/v1/users/657ebb4cc105647ed8c60a9e
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJlbWFpbCI6IkFkbWluQGV4YW1wbGUuY29tIiwiaWQiOiI2NTdlYmI0YmMxMDU2NDdlZDhjNjBhOTYiLCJpc0FkbWluIjp0cnVlLCJpYXQiOjE3MDI4MDU2NjF9.6B2b0UZnktW2twLUDZdPAnwec9BRR2figujqwFyOBAQ


### get user by id with an id of another user (not admin): 401 Unauthorized
GET http://localhost:8080/api/v1/users/657ebb4cc105647ed8c60a9e
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJlbWFpbCI6IlJlZ3VsYXJAZXhhbXBsZS5jb20iLCJpZCI6IjY1N2ViYjRjYzEwNTY0N2VkOGM2MGFhNCIsImlzQWRtaW4iOmZhbHNlLCJpYXQiOjE3MDI4MDU3NDZ9.DcHF_4jLPHc8zFWWGvOi0uxEIBmrfxUYNNVSz5mdqjI



### update a user:
PUT http://localhost:8080/api/v1/users/65cba399cb4c91e0e0c3ad24
Content-Type: application/json
Authorization: bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJlbWFpbCI6Im5veXlAZW1haWwuY29tIiwiaWQiOiI2NWNiYTM5OWNiNGM5MWUwZTBjM2FkMjQiLCJpc0FkbWluIjpmYWxzZSwiaWF0IjoxNzA3OTMwNzA3fQ.UYHeaNUt7wYYOuEMamRLGmJ4bI8pnzS0QCaj4sL1beo

{
  
  "name": "kiara",
  "email": "noyy@email.com",
  "password": "Abc!123Abc"

}


### partial update a user (only isBusiness):
# PATCH http://localhost:8080/api/v1/users/657ec2c6c105647ed8c60ad1
# Content-Type: application/json
# Authorization: bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJlbWFpbCI6Im5veUBlbWFpbC5jb20iLCJpZCI6IjY1N2VjMmM2YzEwNTY0N2VkOGM2MGFkMSIsImlzQWRtaW4iOmZhbHNlLCJpYXQiOjE3MDI4MDY3OTB9.dDBxl9alM7QLa1gIuQYjKrV56nfMDvEI37jd3GgRQzc

# {
#   "isBusiness": true
# }

### delete a user:
DELETE http://localhost:8080/api/v1/users/65c5ef166cd1182384efccc1
Authorization: bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJlbWFpbCI6IkFkbWluQGV4YW1wbGUuY29tIiwiaWQiOiI2NWNiYTUwOGNiNGM5MWUwZTBjM2FkMjciLCJpc0FkbWluIjp0cnVlLCJpYXQiOjE3MDc5MzEyODh9.hoaXs_aWVhb2jiP0K1DAkRngkRe77BNYX_A5BcZlMYQ


### get all products:
GET http://localhost:8080/api/v1/products

### get my products:
GET http://localhost:8080/api/v1/products/my-cart
Authorization: bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJlbWFpbCI6IkFkbWluQGV4YW1wbGUuY29tIiwiaWQiOiI2NTdlYmI0YmMxMDU2NDdlZDhjNjBhOTYiLCJpc0FkbWluIjp0cnVlLCJpYXQiOjE3MDI4MTIyNzF9.XjmFKYicKFyGhWEIBG1zrVqhW20eZW3_7u5_yVf8HAU

### get products by id:
GET http://localhost:8080/api/v1/products/65cd01dd835b273925080e9f


### post a products:
POST http://localhost:8080/api/v1/products
Content-Type: application/json
Authorization: bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJlbWFpbCI6IkFkbWluQGV4YW1wbGUuY29tIiwiaWQiOiI2NWNiYTUwOGNiNGM5MWUwZTBjM2FkMjciLCJpc0FkbWluIjp0cnVlLCJpYXQiOjE3MDc4NDQ5ODR9.eqLidaa_zWWtweQEhzi3Axh3u_g5mr1ZxF-JudbtYoQ

{
  "title": "product 1",
  "description": "Experienced software engineer with a passion for developing innovative programs that expedite the efficiency and effectiveness of organizational success.",
  "image": {
    "url": "https://picsum.photos/200",
    "alt": "John Doe"
  },
  "price":"30"
}

### edit a products:
PUT http://localhost:8080/api/v1/products/65cd01dd835b273925080e9f
Content-Type: application/json
Authorization: bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJlbWFpbCI6IkFkbWluQGV4YW1wbGUuY29tIiwiaWQiOiI2NWNiYTUwOGNiNGM5MWUwZTBjM2FkMjciLCJpc0FkbWluIjp0cnVlLCJpYXQiOjE3MDc5MzQ2MDZ9.C63iQRP3hqQJcJ3iztIQ8uMyzKMOciUUI7dYyobbdQ0

{
  "title": "shoes",
  "description": "Experienced software engineer with a passion for developing innovative programs that expedite the efficiency and effectiveness of organizational success.",
  "image": {
    "url": "https://picsum.photos/200",
    "alt": "John Doe"
  },
  "price":30
}

###like products
PATCH http://localhost:8080/api/v1/products/65cd01dd835b273925080e9f
Authorization: bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJlbWFpbCI6Im5veXlAZW1haWwuY29tIiwiaWQiOiI2NWNiYTM5OWNiNGM5MWUwZTBjM2FkMjQiLCJpc0FkbWluIjpmYWxzZSwiaWF0IjoxNzA3OTM1MzQxfQ.4VT2dYVkofWsBQDN4cAkeW_t1T8crxOpC6HuLk0s6gU

### delete products:
DELETE http://localhost:8080/api/v1/products/65cbb4bdc49c93e7501f3a06
Authorization: bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJlbWFpbCI6Im5veXlAZW1haWwuY29tIiwiaWQiOiI2NWNiYTM5OWNiNGM5MWUwZTBjM2FkMjQiLCJpc0FkbWluIjpmYWxzZSwiaWF0IjoxNzA3OTM1MzQxfQ.4VT2dYVkofWsBQDN4cAkeW_t1T8crxOpC6HuLk0s6gU