### post new user
POST http://localhost:8181/api/v1/users
Content-Type: application/json

{
    "name": {
    "first": "mo",
    //"middle": "c",
    "last": "Cohen"
  },
  "phone": "0512345567",
  "email": "mo@email.com",
  "password": "Abc!123Abc",
  "image": {
    "url": "https://picsum.photos/200/300",
    "alt": "avatar"
  },
  "address": {
    "state": "IL",
    "country": "Israel",
    "city": "Arad",
    "street": "Shoham",
    "houseNumber": 5,
    "zip": 89
  },
  "isBusiness": false
}

###login
POST http://localhost:8181/api/v1/users/login
Content-Type: application/json

{
  "email": "do@email.com",
  "password": "Abc!123Abc"
}

### get all users
GET http://localhost:8181/api/v1/users
Authorization: bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJlbWFpbCI6ImRvQGVtYWlsLmNvbSIsImlkIjoiNjU2MDk5NTNhNTFjODRhNjZkZDY5YzgyIiwiaXNBZG1pbiI6dHJ1ZSwiaWF0IjoxNzAwODMwNDE1fQ.FHkPYzcUsupJizreIPktqW9tgESqkwoUEv2-QyQJ9TE

###get user by id
GET http://localhost:8181/api/v1/users/65609953a51c84a66dd69c83
Authorization: bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJlbWFpbCI6ImRvQGVtYWlsLmNvbSIsImlkIjoiNjU2MDk5NTNhNTFjODRhNjZkZDY5YzgyIiwiaXNBZG1pbiI6dHJ1ZSwiaWF0IjoxNzAwODMxNjAxfQ.f7sGe-c3S3wGVzTdpGhblRuX8FuF6GmGDA6OyEXjJPk


###update/edit user by id:
PUT http://localhost:8181/api/v1/users/6561d54f2d60f2d75803cc85
Authorization: bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJlbWFpbCI6ImRvQGVtYWlsLmNvbSIsImlkIjoiNjU2MWQ1NGYyZDYwZjJkNzU4MDNjYzg1IiwiaXNBZG1pbiI6dHJ1ZSwiaWF0IjoxNzAwOTE0Njk0fQ.4A207OolTA7Cf7Q5JL1feYtqi51iCqA8_yUXqrUCvsc
Content-Type: application/json

{
  "phone":"0522217880"
}


###change isBusiness status:
PATCH http://localhost:8181/api/v1/users/6561e4075dcb05b65509f6ee

###delete user by id:
DELETE http://localhost:8181/api/v1/users/6561d54f2d60f2d75803cc85
Authorization: bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJlbWFpbCI6Im1vQGVtYWlsLmNvbSIsImlkIjoiNjU2MWY4YmVjNjQxYmMxYWJkMmYzZDJiIiwiaXNBZG1pbiI6ZmFsc2UsImlhdCI6MTcwMDkxOTUwOX0.U3TObMVsAJ0DJGLMf3ltoRLuhhulI_q5K8aYX2EXibk



###get all cards
GET http://localhost:8181/api/v1/cards

###get myCards:
GET http://localhost:8181/api/v1/cards/my-cards
//Authorization: bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJlbWFpbCI6Im1vQGVtYWlsLmNvbSIsImlkIjoiNjU2MWY4YmVjNjQxYmMxYWJkMmYzZDJiIiwiaXNBZG1pbiI6ZmFsc2UsImlhdCI6MTcwMDkxOTUwOX0.U3TObMVsAJ0DJGLMf3ltoRLuhhulI_q5K8aYX2EXibk



###create new card
POST http://localhost:8181/api/v1/cards
Authorization: bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJlbWFpbCI6ImRvQGVtYWlsLmNvbSIsImlkIjoiNjU2MWQ1NGYyZDYwZjJkNzU4MDNjYzg1IiwiaXNBZG1pbiI6dHJ1ZSwiaWF0IjoxNzAxMDMxMzMxfQ.UUPvTNoysKhn06F5XxSGCcUgbjW0x4Ux_wQY105Jyxk
Content-Type: application/json

{
  "title": "a wonderful new card",
  "subtitle": "a test value for this card",
  "description": "a test value for new card\na test value for new card\n",
  "phone": "0522217881",
  "email": "dor@gmail.com",
  //"web": "www.bing.com",
  "image": {
    "url": "https://img.izismile.com/img/img13/20201030/640/you_have_never_seen_something_like_this_640_36.jpg",
    "alt": "image of something"
  },
  "address": {
    "state": "IL",
    "country": "Israel",
    "city": "Arad",
    "street": "Shoham",
    "houseNumber": 5,
    "zip": 100
  }
}